apiVersion: v1
kind: Pod
metadata:
  name: pod-amb-configuracio
spec:
  containers:
  - name: el-meu-contenidor
    image: alpine
    command: ["/bin/sh", "-c", "echo El missatge és: $MISSATGE_APP i la clau és: $CLAU_DB; sleep 3600"]
    env:
    - name: MISSATGE_APP
      valueFrom:
        configMapKeyRef:
          name: configuracio-web
          key: MISSATGE
    - name: CLAU_DB
      valueFrom:
        secretKeyRef:
          name: credencials-db
          key: PASSWORD
